name: "Execute Unity Action"
description: "Used for executing an Unity project using a specific installed version. Supports cross-platform."
author: "Neo Chen"
inputs:
  unity_install_dir:
    description: "Root directory to locate Unity installations. Defaults to the OS-specific Unity installation path. Avoid specifying a direct path to a specific Unity version."
  project_path:
    description: "Absolute path to the Unity project directory that you want to operate on. The path should include 'ProjectSettings' folder. Defaults to the GitHub workspace directory."
    default: "${{ github.workspace }}"
    required: true
  log_path:
    description: 'The relative path to project_path for the execution log file. Defaults to "unity_output.log"'
    default: "unity_output.log"
  custom_args:
    description: "Additional command line arguments passed to Unity. Each parameter should start with a dash. If an argument requires a value, place the value directly after the argument, separated by a space."
runs:
  using: "composite"
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: "lts/*"
    - name: Execute Unity
      env:
        unity_install_dir: ${{ inputs.unity_install_dir }}
        project_path: ${{ inputs.project_path }}
        log_path: ${{ inputs.log_path }}
        custom_args: ${{ inputs.custom_args }}
      shell: ${{ runner.os == 'Windows' && 'powershell' || 'bash' }}
      working-directory: ${{ github.action_path }}
      run: npm run start
